export {
  s3,
  getBucketForClassification,
  isGobdClassification,
  isGwgClassification,
  classificationToTier,
  documentTier,
  getBucketForTier,
  type ProtectionTier,
} from './client';
export {
  fetchObjectBytes,
  fetchVerifiedObjectBytes,
  streamVerifiedObject,
  fetchObjectHead,
  bytesResponseBody,
  StoredObjectError,
  UploadRejectedError,
  OBJECT_HEAD_BYTES,
  deleteObject,
  deleteObjectVersion,
  putObjectBytes,
  commitDocumentFromBytes,
  commitBytesWithTier,
  prepareBytesCommitWithTier,
  commitPreparedBytes,
  recoverPreparedBytesCommit,
  sanitizeFilenameForHeader,
  detectMimeFromMagicBytes,
  detectOoxmlMime,
  gobdRetentionUntil,
  gobdRetentionUntilFor,
  gobdRetentionYears,
  retentionUntilForYears,
  gwgRetentionUntil,
  scanBytes,
  MAX_UPLOAD_BYTES,
  type CommitDocumentResult,
  type PreparedBytesCommit,
  type StoredObjectErrorReason,
  type UploadRejectionReason,
  type StoredObjectIntegrity,
  type StoredObjectReadOptions,
  type StoredObjectRef,
  type VerifiedObjectStream,
  type ScanResult,
} from './service';
export {
  checkDeployReadiness,
  type ReadinessReport,
  type ReadinessCheck,
  type ReadinessOptions,
  type CheckStatus,
} from './deploy-readiness';
