export {
  s3,
  getBucketForClassification,
  isGobdClassification,
  isGwgClassification,
  classificationToTier,
  getBucketForTier,
  type ProtectionTier,
} from './client';
export {
  fetchObjectBytes,
  streamObject,
  deleteObject,
  deleteObjectVersion,
  putObjectBytes,
  commitDocumentFromBytes,
  commitBytesWithTier,
  prepareBytesCommitWithTier,
  commitPreparedBytes,
  recoverPreparedBytesCommit,
  sanitizeFilenameForHeader,
  detectMimeFromMagicBytes,
  gobdRetentionUntil,
  gobdRetentionUntilFor,
  gobdRetentionYears,
  retentionUntilForYears,
  gwgRetentionUntil,
  scanBytes,
  MAX_UPLOAD_BYTES,
  type CommitDocumentResult,
  type PreparedBytesCommit,
  type ObjectStream,
  type ScanResult,
} from './service';
export {
  checkDeployReadiness,
  type ReadinessReport,
  type ReadinessCheck,
  type ReadinessOptions,
  type CheckStatus,
} from './deploy-readiness';
