/** STBVV-CALCULATION-001. Current catalogue, checked against the official
 * consolidated text on 2026-08-31. Labels are summaries, source remains visible.
 * A selected rate is a human determination under § 11, never an AI approval. */
export const STBVV_VERSION = 'STBVV-2026-08-31/TABLES-2025-07-01';
export type FeeTable = 'A' | 'B' | 'C' | 'D' | 'Da';
export interface FeeDefinition {
  id: string;
  label: string;
  provision: string;
  source: string;
  kind: 'VALUE' | 'TIME' | 'AMOUNT' | 'EXTERNAL';
  table?: FeeTable;
  min: number;
  max: number;
  denominator: number;
  minimumValue: number;
  valueMultiplier: number;
  valueSign: 'NONNEGATIVE' | 'SIGNED' | 'ABSOLUTE';
  valueHint: string;
  unit: string;
}
function fee(
  id: string,
  label: string,
  table: FeeTable,
  min: number,
  max: number,
  denominator = 10,
  minimumValue = 0,
  valueHint = 'Gegenstandswert nach der verlinkten Vorschrift; mehrere Gegenstände nach §§ 10, 12 prüfen.',
  valueMultiplier = 1,
): FeeDefinition {
  const [section, para, item] = id.split('-');
  const citationItem = item?.replace('zeit', '').replace(/(\d)([a-z])$/, '$1 Buchst. $2');
  const provision =
    section === '37'
      ? `§ 37 Nr. ${item} StBVV`
      : section === '23' && para === '2'
        ? `§ 23 Abs. 2 Satz ${item} StBVV`
        : `§ ${section}${para ? ` Abs. ${para}` : ''}${citationItem ? ` Nr. ${citationItem}` : ''} StBVV`;
  return {
    id,
    label,
    provision,
    source: `https://www.gesetze-im-internet.de/stbgebv/__${section}.html`,
    kind: 'VALUE',
    table,
    min,
    max,
    denominator,
    minimumValue,
    valueHint,
    valueMultiplier,
    valueSign:
      id === '24-1-4' ? 'ABSOLUTE' : ['24-1-3', '24-1-5'].includes(id) ? 'SIGNED' : 'NONNEGATIVE',
    unit: 'Angelegenheit',
  };
}
function time(id: string, label: string): FeeDefinition {
  return {
    ...fee(id, label, 'A', 16.5, 41),
    table: undefined,
    kind: 'TIME',
    denominator: 1,
    valueHint: 'Tatsächlich aufgewandte Minuten; je angefangene Viertelstunde (§ 13).',
    unit: 'Viertelstunde',
  };
}
function amount(id: string, label: string, min: number, max: number, unit: string): FeeDefinition {
  return {
    ...fee(id, label, 'A', min, max),
    table: undefined,
    kind: 'AMOUNT',
    denominator: 1,
    unit,
    valueHint: 'Betrag im gesetzlichen Rahmen und Anzahl der Einheiten fachlich bestimmen.',
  };
}
function external(id: string, label: string, hint: string): FeeDefinition {
  return {
    ...fee(id, label, 'A', 0, 0),
    table: undefined,
    kind: 'EXTERNAL',
    denominator: 1,
    valueHint: hint,
  };
}
const basis35 =
  'Nach § 35 Abs. 2 bereits ermittelter Gegenstandswert. Bilanzberichtigung, höhere Jahresaufwendungen, Fünffachgrenze und 3.000-Euro-Ausnahmen prüfen; Berechnung im Begründungsfeld dokumentieren.';
export const STBVV_CATALOG: readonly FeeDefinition[] = [
  external(
    '2',
    'Sinngemäße Anwendung',
    'Nicht geregelte Tätigkeit: vergleichbare Vorschrift, Berechnung und Begründung gesondert dokumentieren (§ 2).',
  ),
  external(
    '4',
    'Vergütungsvereinbarung',
    'Vereinbarte Vergütung, kein gesetzlicher Tabellenbetrag. Wirksame Vereinbarung und Berechnung müssen gesondert dokumentiert werden.',
  ),
  time('13', 'Zeitgebühr mangels schätzbaren Gegenstandswerts (nicht § 23)'),
  fee('21-1', 'Rat oder Auskunft', 'A', 1, 10),
  external(
    '21-2',
    'Prüfung der Erfolgsaussicht eines Rechtsmittels (RVG)',
    'RVG-Verweis: extern berechneten Betrag und konkrete RVG/VV-Positionen dokumentieren. Kein vollständiger RVG-Rechner.',
  ),
  fee('22-1', 'Gutachten / Antrag auf verbindliche Auskunft', 'A', 10, 30),
  ...(
    [
      ['1', 'Berichtigung einer Erklärung', 2, 10],
      ['2', 'Stundung', 2, 8],
      ['3', 'Anpassung der Vorauszahlungen', 2, 8],
      ['4', 'Billigkeitsfestsetzung', 2, 8],
      ['5', 'Erlass', 2, 8],
      ['6', 'Erstattung § 37 Abs. 2 AO', 2, 8],
      ['7', 'Aufhebung / Änderung eines Bescheids', 2, 10],
      ['8', 'Rücknahme / Widerruf', 4, 10],
      ['9', 'Wiedereinsetzung außerhalb Rechtsbehelf', 4, 10],
      ['10', 'Sonstiger Antrag außerhalb Erklärung', 2, 10],
    ] as const
  ).map(([n, l, min, max]) => fee(`23-1-${n}`, l, 'A', min, max)),
  amount('23-2-1', 'Kassenmitteilung: erstes System je Betriebsstätte', 10, 30, 'Betriebsstätte'),
  amount(
    '23-2-2',
    'Kassenmitteilung: weiteres System derselben Betriebsstätte',
    5,
    20,
    'weiteres System',
  ),
  amount('23-2-3', 'Kassenmitteilung: ausschließlich Abmeldung (einmal)', 10, 30, 'Mitteilung'),
  fee(
    '24-1-1',
    'Einkommensteuererklärung',
    'A',
    1,
    6,
    10,
    8000,
    'Summe positiver Einkünfte, ohne Einkünfteermittlung.',
  ),
  fee(
    '24-1-2',
    'Gesonderte Feststellung der Einkünfte',
    'A',
    1,
    5,
    10,
    8000,
    'Summe positiver Einkünfte, ohne Einkünfteermittlung.',
  ),
  fee(
    '24-1-3',
    'Körperschaftsteuererklärung',
    'A',
    2,
    8,
    10,
    16000,
    'Einkommen vor Verlustabzug. Organgesellschaft vor Zurechnung; Organträger entsprechend kürzen.',
  ),
  fee(
    '24-1-4',
    'Mindeststeuererklärung',
    'A',
    1,
    8,
    10,
    16000,
    'Mindeststeuergewinn oder -verlust; vom absoluten Betrag 1 %. Anrechnung Mindeststeuerbericht prüfen.',
    0.01,
  ),
  fee(
    '24-1-5',
    'Gewerbesteuererklärung',
    'A',
    1,
    6,
    10,
    8000,
    'Gewerbeertrag vor Freibetrag und Gewerbeverlust.',
  ),
  fee(
    '24-1-6',
    'Gewerbesteuerzerlegung',
    'A',
    1,
    6,
    10,
    4000,
    'Arbeitslöhne als Zerlegungsmaßstab; davon 10 %.',
    0.1,
  ),
  fee(
    '24-1-7',
    'Umsatzsteuer-Voranmeldung',
    'A',
    1,
    6,
    10,
    650,
    'Summe Entgelte einschließlich Reverse-Charge-Entgelte; davon 10 %. Abgeltung durch Buchführung prüfen.',
    0.1,
  ),
  fee(
    '24-1-8',
    'Umsatzsteuer-Jahreserklärung',
    'A',
    1,
    8,
    10,
    8000,
    'Summe Entgelte einschließlich Reverse-Charge-Entgelte; davon 10 %.',
    0.1,
  ),
  fee(
    '24-1-10',
    'Vermögensteuer / Vermögensfeststellung',
    'A',
    1,
    18,
    20,
    12500,
    'Rohvermögen. Für andere als natürliche Personen Mindestwert 25.000 Euro auswählen.',
  ),
  fee('24-1-11', 'Feststellung BewG / ErbStG', 'A', 1, 18, 20, 25000, 'Erklärter Wert.'),
  fee(
    '24-1-11a',
    'Grundsteuer-Feststellung / Festsetzung',
    'A',
    1,
    9,
    20,
    25000,
    'Grundsteuerwert; alternativ Messbetrag / Messzahl gemäß § 15 Abs. 1 Nr. 2 a GrStG. Bereits dividierten Wert eingeben.',
  ),
  fee(
    '24-1-12',
    'Erbschaftsteuererklärung',
    'A',
    2,
    10,
    10,
    16000,
    'Erwerb vor Schulden und Lasten, ohne Zugewinnausgleichsermittlung.',
  ),
  fee('24-1-13', 'Schenkungsteuererklärung', 'A', 2, 10, 10, 16000, 'Rohwert der Schenkung.'),
  fee(
    '24-1-14',
    'Kapitalertragsteueranmeldung / weitere Erklärung',
    'A',
    1,
    6,
    20,
    4000,
    'Summe kapitalertragsteuerpflichtiger Kapitalerträge.',
  ),
  fee(
    '24-1-15',
    'Lohnsteuer-Anmeldung',
    'A',
    1,
    6,
    20,
    1000,
    'Arbeitslöhne einschließlich sonstiger Bezüge; davon 20 %. Abgeltung durch Lohnabrechnung prüfen.',
    0.2,
  ),
  fee(
    '24-1-16',
    'Einfuhr- / Ausfuhrabgaben',
    'A',
    1,
    3,
    10,
    1000,
    'Abgabenbetrag bei höchsten in Betracht kommenden Abgabensätzen.',
  ),
  fee(
    '24-1-17',
    'Verbrauchsteuern',
    'A',
    1,
    3,
    10,
    1000,
    'Angemeldeter bzw. festgesetzter Betrag.',
  ),
  fee(
    '24-1-18',
    'Verbrauchsteuervergütung / -erstattung',
    'A',
    1,
    3,
    10,
    1000,
    'Beantragte Vergütung / Erstattung außerhalb monatlicher Anmeldung.',
  ),
  fee('24-1-19', 'Investitionszulage', 'A', 1, 6, 10, 0, 'Bemessungsgrundlage.'),
  fee('24-1-20', 'Steuervergütung § 4a UStG', 'A', 1, 6, 10, 0, 'Beantragte Vergütung.'),
  fee('24-1-21', 'Vorsteuervergütung', 'A', 1, 6, 10, 1300, 'Beantragte Vergütung.'),
  fee(
    '24-1-22',
    'Kapitalertragsteuererstattung / KSt-Vergütung',
    'A',
    1,
    6,
    10,
    1000,
    'Beantragte Erstattung.',
  ),
  fee('24-1-23', 'Kindergeldantrag', 'A', 2, 10, 10, 0, 'Beantragtes Jahreskindergeld.'),
  fee(
    '24-1-25',
    'Steuerabzug Bauleistungen',
    'A',
    1,
    6,
    10,
    1000,
    'Angemeldeter Steuerabzugsbetrag.',
  ),
  fee(
    '24-1-26',
    'Sonstige Steuererklärungen',
    'A',
    1,
    6,
    10,
    8000,
    'Jeweilige Bemessungsgrundlage.',
  ),
  fee('24-3', 'Zugewinnausgleichsforderung', 'A', 5, 15, 10, 12500, 'Ermittelter Betrag.'),
  fee('24-4', 'Lohnsteuer-Ermäßigung', 'A', 1, 4, 20, 4500, 'Voraussichtlicher Jahresarbeitslohn.'),
  ...[
    'Mitteilung § 138 Abs. 2 AO',
    'Verrechenbarer Verlust § 15a EStG',
    'Begünstigungsgewinn § 34a EStG',
    'Sonstiger Antrag / Meldung EStG',
    'Mindeststeuerbericht',
    'Lohnsummen- / Behaltensfristüberwachung ErbStG',
    'Anzeige § 30 ErbStG',
    'Fahrzeuglieferungsmeldung',
  ].map((l, i) => time(`24-5-${i + 1}`, l)),
  fee(
    '25-1',
    'Einnahmenüberschussrechnung',
    'B',
    5,
    30,
    10,
    17500,
    'Höherer Betrag aus Betriebseinnahmen und Betriebsausgaben; je gesonderter Rechnung.',
  ),
  time('25-2', 'Zusätzliche Vorarbeiten EÜR'),
  fee('25-4', 'Erläuterungsbericht EÜR', 'B', 2, 12, 10, 17500, 'Wie EÜR (§ 25 Abs. 1).'),
  fee(
    '26-1',
    'Landwirtschaftlicher Durchschnittssatzgewinn',
    'B',
    5,
    20,
    10,
    0,
    'Summe des Gewinns nach Durchschnittssätzen; je gesondertem Betrieb.',
  ),
  fee(
    '27-1',
    'Überschuss der Einnahmen über Werbungskosten',
    'A',
    1,
    12,
    20,
    8000,
    'Höherer Betrag aus Einnahmen und Werbungskosten; je gesonderter Überschussrechnung.',
  ),
  time('27-3', 'Zusätzliche Vorarbeiten Überschussrechnung'),
  time('28', 'Prüfung von Steuerbescheiden'),
  time('29-1', 'Teilnahme an Prüfungen / Nachschauen'),
  fee('29-2', 'Schriftliche Einwendungen gegen Prüfungsbericht', 'A', 5, 10),
  fee(
    '30',
    'Selbstanzeige',
    'A',
    10,
    30,
    10,
    8000,
    'Summe berichtigter, ergänzter und nachgeholter Angaben zu Einkünften; sachliche Voraussetzungen separat prüfen.',
  ),
  fee('31', 'Besprechung', 'A', 5, 10),
  time('32', 'Einrichtung der Buchführung / Aufzeichnungen'),
  ...(
    [
      ['1', 'Buchführung einschließlich Kontieren', 2, 12, 10],
      ['2', 'Nur Kontieren', 1, 6, 10],
      ['3', 'Buchführung nach Mandantenkontierung', 1, 6, 10],
      ['4', 'Buchführung nach Mandantendaten', 1, 10, 20],
      ['5', 'Überwachung der Buchführung', 1, 6, 10],
    ] as const
  ).map(([n, l, min, max, d]) => ({
    ...fee(
      `33-${n}`,
      l,
      'C',
      min,
      max,
      d,
      0,
      'Höherer Jahresbetrag nach § 33 Abs. 6: Umsatz/Aufwand bzw. Einnahmen/Ausgaben. Softwarevergütung gesondert dokumentieren.',
    ),
    unit: 'Monat',
  })),
  time('33-7', 'Sonstige Buchführungshilfe'),
  amount('34-1', 'Lohnkonto einrichten / Stammdaten erstmalig aufnehmen', 6, 19, 'Arbeitnehmer'),
  amount('34-2', 'Lohnabrechnung / Lohnkonto', 6, 30, 'Arbeitnehmer und Abrechnungszeitraum'),
  amount(
    '34-3',
    'Lohnabrechnung nach Mandantenbuchungen',
    2.5,
    9.5,
    'Arbeitnehmer und Abrechnungszeitraum',
  ),
  amount(
    '34-4',
    'Lohnabrechnung nach Mandantendaten',
    1.2,
    4.2,
    'Arbeitnehmer und Abrechnungszeitraum',
  ),
  time('34-5', 'Sonstige Lohnsteuerhilfe'),
  ...(
    [
      ['1a', 'Jahresabschluss', 10, 40],
      ['1b', 'Anhang erstellen', 2, 12],
      ['2', 'Zwischen- / vorläufiger Abschluss', 10, 40],
      ['3a', 'Steuerliches Ergebnis ableiten', 2, 10],
      ['3b', 'Steuerbilanz entwickeln', 5, 12],
      ['4', 'Eröffnungsbilanz', 5, 12],
      ['5', 'Auseinandersetzungsbilanz', 5, 20],
      ['6', 'Erläuterungsbericht Abschluss', 2, 12],
      ['7a', 'Mitwirkung Jahresabschluss', 2, 10],
      ['7b', 'Mitwirkung Anhang', 2, 4],
      ['7c', 'Mitwirkung Lagebericht', 2, 4],
    ] as const
  ).map(([n, l, min, max]) => fee(`35-1-${n}`, l, 'B', min, max, 10, 0, basis35)),
  time('35-3', 'Inventurunterlagen / Abschlussvorarbeiten'),
  time('36-1', 'Prüfung / Bestätigung (Zeitgebühr)'),
  fee(
    '36-2-1',
    'Prüfung Bilanz / Rechnung / Buchführung (zusätzlich Zeit)',
    'B',
    2,
    10,
    10,
    0,
    basis35,
  ),
  time('36-2-1zeit', 'Zusätzliche Zeitgebühr zur Prüfung § 36 Abs. 2 Nr. 1'),
  time('36-2-2', 'Schriftlicher Prüfungsbericht'),
  fee(
    '37-1-1',
    'Vermögens- / Finanzstatus erstellen',
    'B',
    5,
    15,
    10,
    0,
    'Summe der Vermögenswerte bzw. Finanzwerte.',
  ),
  fee(
    '37-1-2',
    'Status aus vorliegenden Zahlen',
    'B',
    2,
    6,
    10,
    0,
    'Summe der Vermögenswerte bzw. Finanzwerte.',
  ),
  fee(
    '37-1-3',
    'Erläuterungsbericht Status',
    'B',
    1,
    6,
    10,
    0,
    'Summe der Vermögenswerte bzw. Finanzwerte.',
  ),
  fee(
    '38-1',
    'Bescheinigung zur Beachtung steuerrechtlicher Vorschriften in Vermögensübersichten / Erfolgsrechnungen',
    'B',
    1,
    6,
    10,
    0,
    basis35,
  ),
  time('38-2', 'Mitwirkung bei Bescheinigungen in Steuersachen'),
  ...(
    [
      ['2', '1', 'Landwirtschaftliche Buchführung vollständig', 3, 20, 10],
      ['2', '2', 'Landwirtschaft: Mandantenkontierung', 3, 20, 20],
      ['2', '3', 'Landwirtschaft: Mandantendaten', 1, 16, 20],
      ['2', '4', 'Landwirtschaft: Überwachung', 1, 6, 10],
      ['3', '1', 'Landwirtschaft: Abschlussvorarbeiten', 1, 5, 10],
      ['3', '2', 'Landwirtschaft: Abschluss', 3, 10, 10],
      ['3', '3', 'Landwirtschaft: steuerlichen Abschluss ableiten', 3, 10, 20],
      ['3', '4', 'Landwirtschaft: Mitwirkung Abschluss', 1, 10, 20],
      ['3', '5', 'Landwirtschaft: Prüfung Abschluss', 1, 8, 10],
      ['3', '6', 'Landwirtschaft: Erläuterungsbericht', 1, 8, 10],
    ] as const
  ).map(([p, n, l, min, max, d]) => ({
    ...fee(
      `39-${p}-${n}`,
      l,
      'D',
      min,
      max,
      d,
      0,
      'Jahresumsatz + Privateinlagen oder höhere Aufwendungen + Privatentnahmen. Gewichtete Fläche nach § 39 Abs. 6 zusätzlich eingeben; bei Abs. 3 wird Mehrbetrag über 100.000 halbiert.',
    ),
    unit: p === '2' ? 'Jahr' : 'Angelegenheit',
  })),
  fee(
    '39-4-1',
    'Landwirtschaft: Buchführung einrichten',
    'Da',
    1,
    6,
    10,
    0,
    'Gewichtete Betriebsfläche nach § 39 Abs. 6.',
  ),
  fee(
    '39-4-2',
    'Landwirtschaft: Anfangswerte erfassen',
    'Da',
    3,
    15,
    10,
    0,
    'Gewichtete Betriebsfläche nach § 39 Abs. 6.',
  ),
  external(
    '40',
    'Rechtsbehelfe, gerichtliche Verfahren, Vollstreckung (RVG)',
    '§ 40 verweist auf das RVG. Konkrete RVG/VV-Position, Rechtsstand und extern geprüfte Berechnung müssen angegeben werden. Keine stille Anwendung der StBVV-Tabelle A.',
  ),
];

export const STBVV_GENERAL_RULES = [
  ['§§ 1–3', 'Anwendungsbereich, sinngemäße Anwendung, Auslagen'],
  [
    '§§ 4, 4a, 4b',
    'Vereinbarung, Unterschreiten der gesetzlichen Vergütung, Folgen fehlerhafter Vereinbarung: gesonderte Prüfung',
  ],
  [
    '§§ 5–9',
    'Mehrere Steuerberater/Auftraggeber, Fälligkeit, Vorschuss, nachvollziehbare Rechnung',
  ],
  ['§§ 10–12', 'Gegenstandswerte, billiges Ermessen, dieselbe Angelegenheit und Anrechnungen'],
  ['§ 13', 'Zeitgebühr nur im gesetzlichen Anwendungsfall; kein Ersatz für § 23'],
  ['§ 14', 'Aufgehoben; keine neue Pauschalgebühr aus dieser Vorschrift'],
  ['§§ 15–20', 'Umsatzsteuer, Post, Dokumente, Reisen, Auslagenverteilung, Sitzverlegung'],
  ['§ 41', 'Übergang: nur ausgewählter aktueller Rechtsstand; keine automatische Rückberechnung'],
] as const;
